# Generated by Django 5.1 on 2024-08-11 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rankerapi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='restaurants',
            field=models.JSONField(default=list),
        ),
    ]
