# Generated by Django 5.1 on 2024-08-11 22:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rankerapi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sessionuser',
            name='session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='users', to='rankerapi.session'),
        ),
    ]
