# Generated by Django 5.1 on 2024-08-11 22:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rankerapi', '0002_alter_sessionuser_session'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sessionuser',
            name='session',
        ),
        migrations.AddField(
            model_name='sessionuser',
            name='session_code',
            field=models.ForeignKey(default='test', on_delete=django.db.models.deletion.CASCADE, related_name='users', to='rankerapi.session'),
            preserve_default=False,
        ),
    ]
