# Generated by Django 5.1 on 2024-08-11 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rankerapi', '0002_session_restaurants'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='restaurants',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
