# Generated by Django 5.1 on 2024-08-11 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rankerapi', '0003_remove_sessionuser_session_sessionuser_session_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('photo_url', models.URLField(blank=True)),
                ('rating', models.FloatField()),
                ('vetoed', models.BooleanField(default=False)),
            ],
        ),
        migrations.RemoveField(
            model_name='session',
            name='restaurants',
        ),
    ]
