# Generated by Django 5.1 on 2024-08-11 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rankerapi', '0004_restaurant_remove_session_restaurants'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='restaurants',
            field=models.ManyToManyField(blank=True, to='rankerapi.restaurant'),
        ),
    ]
