# Generated by Django 5.1 on 2024-08-12 00:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rankerapi', '0005_session_restaurants'),
    ]

    operations = [
        migrations.RenameField(
            model_name='restaurant',
            old_name='vetoed',
            new_name='veto',
        ),
    ]
